### ISSUE TITLE
XML format

### ISSUE THREAD

**Issue by 22nra** [GrahamM/CCDigitalHygroTherm#1]
Hello very interested in using your HyGroTherm with my PiHomeGuard.co.uk project. 
Will the xml format be the same as usual standard format on CC Envi?
thanks and regards,
jamie

**Comment by GrahamM** [comment]
Hi Jamie,

In short, the XML format is the usual standard format for impulse sensors. It's documented in Current Cost's XML Output Description[1] in section 3, titled 'Real-Time Output from "Meter Impulse" sensors'. Be aware that I packed the 16 bit temperature, the 8 bit humidity and an 8 bit checksum into the 32bit impulse value, so the XML output will have a 32 bit impulse value in decimal. You'll need to extract the temperature/humidity/checksum from that - effectively just a bit of bit masking and shifting though, I was limited to what the CC Envi will accept, hence the slightly odd format!

[1] http://www.currentcost.com/download/Envi%20XML%20v19%20-%202011-01-11.pdf

**Comment by 22nra** [comment]
Hi Graham, 
many thanks for your prompt reply and sorry for the below questions.

I currently have a couple of temp sensors using the CC analogue board and tmp36/37 sensors.
Have also been trying to develop a humidity sensor, again using analogue but current drain too high 
The Temp sensors work fairly well but I really want to try and use the digital type DHT22 you mention in your blog.

My knowledge of digital engineering is limited but from what I understand the below are the rough steps that need to be taken;
Obtain suitable compiler (use Raspberry Pi?) and compile your c code in github ?
Use suitable tool to flash new firmware to CC devboard ?
Modify dev board pulldown/pullup resistors and connect digital o/p from DHT22 to ? 
I then have to decrypt the 32bit value from the sensor into the two temp & humidity values, should be ok with this bit.

Normally the CC board will pulse about every 6 secs your modified firmware has changed this to 80 secs, this of course will extend the battery life 

Flash tool:
As a hobby I fly quadcopters and have used the below device to flash the quad’s firmware.
http://www.banggood.com/USBASP-USBISP-3_3-5V-AVR-Downloader-Programmer-With-ATMEGA8-ATMEGA128-p-934425.html
Are you able to recommend a suitable CC dev board flash hardware/software.
Came across below which should work with the PIC16F689 processor
http://www.banggood.com/Wholesale-K150-ICSP-USB-PIC-Automatic-Programming-Develop-Microcontroller-Programmer-p-43254.html

best regards,
jamie

**Comment by GrahamM** [comment]
Assuming you don't need to modify the code, I'd suggest:
- Pick HEX file up from dist/default/production in the repository. (It's already compiled)
- Use suitable tool to flash hex to Dev Board.
- Remove pulldown (R10) resistor from board.
- Add pull up resistor (around 5K - not critical)  across the two sensor terminals.
- Connect DHT22 , so the digital output goes to the same terminal that leads to where R10 was.
- Provide power to board and pair with CC Envi.
- Interpret XML output.

I don't know if the USBASP can actually program a PIC16 device or not, I don't have experience with the device. Personally, I'm using an original PICKit2 programmer. The K150 programmer looks like it should work in theory - again, I've not used it to know.

I'm assuming that you have a digital dev board (although you've mentioned analog), as the code I've written is targeted for it. I don't know what differences there are between the analog boards and digital boards.

**Comment by 22nra** [comment]
Thanks again Graham.
Yes - I'll be using the digital board.
I am now on the digital engineering learning curve :)
cheers,
Jamie
pihomeguard@gmail.com

**Comment by 22nra** [comment]
Making progress - but need wee 32bit help - sorry:
Using the K150 programmer I managed to flash the PIC16F689 with your Hex file, everything worked fine :)
One thing to maybe add to the readme is how the ISCP has to have its own cable, I got below from Aedan's post:  " ISCP connector details
ISCP       CCDB
1 VPP     4 
2 VCC     1 
3 GND     5 
4 PGD     3 
5 PGC     2

This shows the mapping from ICSP pins to the CC dev board pins, assuming that pin 1 is closest to the switch. Note that both rows of pins are identical, so it doesn't matter which you connect to"

Removed the pulldown and added a 5K across the board +ve -ve contacts.
I paired Ch1 with the CC128 and as expected it's now seem as a "water" device, only pulses every 80secs, very low current drain :)
I can now see sensor1 in the XML but I'm having trouble understanding the 32bit number.
My xml has:  <imp>0738252290</imp>
As mentioned this is a 32bit number
So I convert the number to binary but only get 30bits 101100000000001101011000000010
I tried adding two 0's to front of number but I still cant make sense of the calculation
Can you please take me through how this number is then split into temp & humidity.
Could you also give an example of a negative temp. 
best regards,
jamie
update: Think I've cracked the code was reading it wrong way round !
0738252290 decimal
00101100 00000000 11010110 00000010  32bit
00101100 = 44%
11010110 = 21.4 degC

first 8bits checksum, next16bits temp degC, last 8 bits humidity
Just got to figure out -ve temps now.

another update:
Have now figured out negative temps, stuffed sensor in freezer!
Sensor1 746618153 
  32Bit 00101100 1 00000000111110100101001 
Humidity:44%  Temperature: -12.5
If bit16 of temp is one, temp is negative, all sorted.
J :)

**Comment by GrahamM** [comment]
I'm glad you got it sorted - I'm guessing I got bitten by some endian weirdness I missed, as I fill the transmit order as such:

datapacket.value_high=Humi & 0xFF;      // Humidity
    datapacket.value_midh=DHTData[2];       // Temperature high
    datapacket.value_midl=DHTData[3];       // Temperature low
    datapacket.value_low=(
            datapacket.value_high+datapacket.value_midh+datapacket.value_midl
            ) & 0xff;  // checksum

Would be good to see what you're doing with this as a whole!

**Comment by 22nra** [comment]
Hi Graham, please take a look at:
https://play.google.com/store/apps/details?id=com.zorac.hcgdemo&hl=en
It would be nice to contact you direct.
